// The automation shim of the prototype sandbox and the page-ops core shared
// with dsh-browser's full-scope driver. No imports: this module is loaded
// standalone and its output is compared byte for byte against the historical
// frozen shim, so a refactor here cannot silently change what prototype pages
// receive.

/** Version of the frozen composed shim below. */
export const BUNDLED_SHIM_VERSION = '2'

/**
 * The page-side automation semantics shared by both drivers: find-by-text,
 * native setter for inputs, and the ops object (click/fill/read/eval/
 * wait_for/wait_stable/console_dump). A statement fragment — it expects to run inside an
 * IIFE scope that also declares `buffer` (the console ring), which is what the
 * composed shim's header does.
 */
export const PAGE_OPS_SOURCE = [
  'function findByText(text) {',
  "  var nodes = document.querySelectorAll('button, a, [role=button], input[type=button], input[type=submit], label, li, span, div');",
  "  var needle = String(text).trim().toLowerCase();",
  "  for (var i = 0; i < nodes.length; i++) {",
  "    var t = (nodes[i].textContent || '').trim().toLowerCase();",
  "    if (t && t.indexOf(needle) !== -1 && nodes[i].offsetParent !== null) return nodes[i];",
  "  }",
  "  return null;",
  "}",
  "function one(el) { el.scrollIntoView({ block: 'center' }); el.click(); return { clicked: true, tag: el.tagName, text: (el.textContent || el.value || '').trim().slice(0, 120) }; }",
  'function roleOf(el) {',
  "  var explicit = el.getAttribute && el.getAttribute('role');",
  "  if (explicit) return explicit.trim().toLowerCase();",
  "  var tag = el.tagName ? el.tagName.toLowerCase() : '';",
  "  if (tag === 'button') return 'button';",
  "  if (tag === 'a' && el.hasAttribute('href')) return 'link';",
  "  if (tag === 'select') return 'combobox';",
  "  if (tag === 'textarea') return 'textbox';",
  "  if (tag === 'input') {",
  "    var t = (el.getAttribute('type') || 'text').toLowerCase();",
  "    if (t === 'submit' || t === 'button' || t === 'reset' || t === 'file') return 'button';",
  "    if (t === 'checkbox') return 'checkbox';",
  "    if (t === 'radio') return 'radio';",
  "    if (t === 'range') return 'slider';",
  "    return 'textbox';",
  "  }",
  "  if (tag === 'img') return 'img';",
  "  if (/^h[1-6]$/.test(tag)) return 'heading';",
  "  if (tag === 'li') return 'listitem';",
  "  return '';",
  '}',
  'function accessibleName(el) {',
  "  var aria = el.getAttribute && el.getAttribute('aria-label');",
  "  if (aria && aria.trim()) return aria.trim();",
  "  var labelledby = el.getAttribute && el.getAttribute('aria-labelledby');",
  "  if (labelledby) {",
  '    var parts = [];',
  "    labelledby.split(/\\s+/).forEach(function (id) { var n = document.getElementById(id); if (n) parts.push((n.textContent || '').trim()); });",
  "    if (parts.length) return parts.join(' ').trim();",
  '  }',
  "  if (el.tagName === 'INPUT') {",
  "    var t = (el.getAttribute('type') || 'text').toLowerCase();",
  "    if (t === 'submit' || t === 'button' || t === 'reset') return (el.value || '').trim();",
  '  }',
  "  var img = el.querySelector && el.querySelector('img[alt]');",
  "  if (img) return (img.getAttribute('alt') || '').trim();",
  "  if (el.getAttribute && el.getAttribute('title')) return el.getAttribute('title').trim();",
  "  var ph = el.getAttribute && el.getAttribute('placeholder');",
  "  return ((el.textContent || '') + ' ' + (ph || '')).trim();",
  '}',
  '/** Accessible lookup: role + accessible name, the robust way to hit a control. */',
  'function findByRole(role, name) {',
  "  var want = String(role || '').trim().toLowerCase();",
  "  var needle = String(name || '').trim().toLowerCase();",
  "  var all = document.querySelectorAll('button, a, input, select, textarea, [role], img, h1, h2, h3, h4, h5, h6, li');",
  '  for (var i = 0; i < all.length; i++) {',
  '    var el = all[i];',
  "    if (!el.getClientRects || el.getClientRects().length === 0) continue;",
  '    if (roleOf(el) !== want) continue;',
  "    var label = accessibleName(el).toLowerCase();",
  "    if (!needle || label.indexOf(needle) !== -1) return el;",
  '  }',
  '  return null;',
  '}',
  "function setNative(el, value) {",
  "  var proto = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;",
  "  var setter = Object.getOwnPropertyDescriptor(proto, 'value').set;",
  "  setter.call(el, value);",
  "  el.dispatchEvent(new Event('input', { bubbles: true }));",
  "  el.dispatchEvent(new Event('change', { bubbles: true }));",
  "}",
  "var ops = {",
  "  click: function (a) {",
  "    var el = a.role ? findByRole(a.role, a.name) : (a.selector ? document.querySelector(a.selector) : findByText(a.text));",
  "    if (!el) throw new Error('element not found: ' + (a.role ? a.role + ' \"' + (a.name || '') + '\"' : (a.selector || a.text)));",
  "    return one(el);",
  "  },",
  "  fill: function (a) {",
  "    var el = a.role ? findByRole(a.role, a.name) : document.querySelector(a.selector);",
  "    if (!el) throw new Error('element not found: ' + (a.role ? a.role + ' \"' + (a.name || '') + '\"' : a.selector));",
  "    setNative(el, String(a.value));",
  "    return { filled: true, value: String(a.value).slice(0, 120) };",
  "  },",
  "  read: function (a) {",
  "    var el = document.querySelector(a.selector);",
  "    if (!el) throw new Error('element not found: ' + a.selector);",
  "    if (a.attr) return el.getAttribute(a.attr);",
  "    return el.value !== undefined && el.tagName !== 'DIV' && el.tagName !== 'SPAN' ? el.value : (el.textContent || '').trim();",
  "  },",
  "  eval: function (a) {",
  "    var fn = new Function('return (' + a.code + ')');",
  "    return fn();",
  "  },",
  "  wait_for: function (a) {",
  "    var deadline = Date.now() + (a.timeoutMs || 5000);",
  "    return new Promise(function (resolveP, rejectP) {",
  "      (function check() {",
  "        var el = document.querySelector(a.selector);",
  "        if (el) return resolveP({ found: true });",
  "        if (Date.now() > deadline) return rejectP(new Error('wait_for timeout: ' + a.selector));",
  "        setTimeout(check, 120);",
  "      })();",
  "    });",
  "  },",
  "  wait_stable: function (a) {",
  "    // Settles once the DOM has been quiet for quietMs with the page loaded,",
  "    // or at the deadline; never throws, like the browser tool's wait_stable.",
  "    // The deadline stays under the tab's 9 s cap on a shim answer.",
  "    var quiet = Math.min(Number(a.quietMs) || 500, 5000);",
  "    var cap = Math.min(Number(a.timeoutMs) || 8000, 8500);",
  "    return new Promise(function (resolveP) {",
  "      var last = Date.now(), started = Date.now();",
  "      var obs = new MutationObserver(function () { last = Date.now(); });",
  "      try { obs.observe(document.documentElement, { subtree: true, childList: true, attributes: true, characterData: true }); } catch (e) {}",
  "      (function check() {",
  "        var idle = Date.now() - last;",
  "        var busy = document.readyState !== 'complete';",
  "        if ((idle >= quiet && !busy) || Date.now() - started >= cap) {",
  "          try { obs.disconnect(); } catch (e) {}",
  "          resolveP({ stable: idle >= quiet && !busy, quietMs: idle, elapsedMs: Date.now() - started });",
  "          return;",
  "        }",
  "        setTimeout(check, 100);",
  "      })();",
  "    });",
  "  },",
  "  console_dump: function () { return { entries: buffer }; },",
  "};",
].join('\n')

/** The composed frozen shim: header + shared ops + footer, byte-identical to the historical single string. */
export const BUNDLED_SHIM_JS = [
  '(function(){',
  'if (window.__DSH_PROTOTYPE_SHIM__) return;',
  `window.__DSH_PROTOTYPE_SHIM__ = ${JSON.stringify(BUNDLED_SHIM_VERSION)};`,
  'var buffer = [];',
  'var MAX = 200;',
  'function push(level, text) {',
  '  var entry = { level: level, text: String(text), time: new Date().toISOString() };',
  '  buffer.push(entry); if (buffer.length > MAX) buffer.shift();',
  "  try { parent.postMessage({ source: 'dsh-prototype-shim', console: entry }, '*'); } catch (e) {}",
  '}',
  "['error','warn'].forEach(function (level) {",
  '  var original = console[level].bind(console);',
  '  console[level] = function () {',
  "    var parts = []; for (var i = 0; i < arguments.length; i++) { try { parts.push(typeof arguments[i] === 'object' ? JSON.stringify(arguments[i]) : String(arguments[i])); } catch (e) { parts.push('[unserializable]'); } }",
  "    push(level, parts.join(' '));",
  '    original.apply(null, arguments);',
  '  };',
  '});',
  "window.addEventListener('error', function (e) { push('error', 'Uncaught: ' + e.message + ' @ ' + (e.filename || '') + ':' + (e.lineno || 0)); });",
  "window.addEventListener('unhandledrejection', function (e) { push('error', 'Unhandled rejection: ' + (e.reason && (e.reason.stack || e.reason.message) || String(e.reason))); });",
  PAGE_OPS_SOURCE,
  "window.addEventListener('message', function (e) {",
  "  var cmd = e.data;",
  "  if (!cmd || cmd.source !== 'dsh-prototype' || !cmd.id) return;",
  '  var op = ops[cmd.op];',
  "  if (!op) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: false, error: 'unknown op ' + cmd.op }, '*'); return; }",
  '  Promise.resolve().then(function () { return op(cmd); })',
  "    .then(function (result) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: true, result: result, consoleTail: buffer.slice(-20) }, '*'); })",
  "    .catch(function (err) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: false, error: String((err && err.message) || err) }, '*'); });",
  '});',
  '})();',
].join('\n')

/**
 * The same ops as an expression for drivers that execute them without the
 * postMessage plumbing (the full-scope WebContentsView in the desktop app).
 * Returns the ops object plus `findByText` for text-based waiting.
 */
export function pageOpsExpression() {
  return `(function(){\n${PAGE_OPS_SOURCE}\n;return { ops: ops, findByText: findByText, findByRole: findByRole };\n})()`
}
