// The automation shim of the prototype sandbox and the page-ops core shared
// with dsh-browser's full-scope driver. No imports: this module is loaded
// standalone and its output is compared byte for byte against the historical
// frozen shim, so a refactor here cannot silently change what prototype pages
// receive.

/** Version of the frozen composed shim below. */
export const BUNDLED_SHIM_VERSION = '1'

/**
 * The page-side automation semantics shared by both drivers: find-by-text,
 * native setter for inputs, and the ops object (click/fill/read/eval/
 * wait_for/console_dump). A statement fragment — it expects to run inside an
 * IIFE scope that also declares `buffer` (the console ring), which is what the
 * composed shim's header does.
 */
export const PAGE_OPS_SOURCE = [
  'function findByText(text) {',
  "  var nodes = document.querySelectorAll('button, a, [role=button], input[type=button], input[type=submit], label, li, span, div');",
  "  var needle = String(text).trim().toLowerCase();",
  "  for (var i = 0; i < nodes.length; i++) {",
  "    var t = (nodes[i].textContent || '').trim().toLowerCase();",
  "    if (t && t.indexOf(needle) !== -1 && nodes[i].offsetParent !== null) return nodes[i];",
  "  }",
  "  return null;",
  "}",
  "function one(el) { el.scrollIntoView({ block: 'center' }); el.click(); return { clicked: true, tag: el.tagName, text: (el.textContent || el.value || '').trim().slice(0, 120) }; }",
  'function roleOf(el) {',
  "  var explicit = el.getAttribute && el.getAttribute('role');",
  "  if (explicit) return explicit.trim().toLowerCase();",
  "  var tag = el.tagName ? el.tagName.toLowerCase() : '';",
  "  if (tag === 'button') return 'button';",
  "  if (tag === 'a' && el.hasAttribute('href')) return 'link';",
  "  if (tag === 'select') return 'combobox';",
  "  if (tag === 'textarea') return 'textbox';",
  "  if (tag === 'input') {",
  "    var t = (el.getAttribute('type') || 'text').toLowerCase();",
  "    if (t === 'submit' || t === 'button' || t === 'reset' || t === 'file') return 'button';",
  "    if (t === 'checkbox') return 'checkbox';",
  "    if (t === 'radio') return 'radio';",
  "    if (t === 'range') return 'slider';",
  "    return 'textbox';",
  "  }",
  "  if (tag === 'img') return 'img';",
  "  if (/^h[1-6]$/.test(tag)) return 'heading';",
  "  if (tag === 'li') return 'listitem';",
  "  return '';",
  '}',
  'function accessibleName(el) {',
  "  var aria = el.getAttribute && el.getAttribute('aria-label');",
  "  if (aria && aria.trim()) return aria.trim();",
  "  var labelledby = el.getAttribute && el.getAttribute('aria-labelledby');",
  "  if (labelledby) {",
  '    var parts = [];',
  "    labelledby.split(/\\s+/).forEach(function (id) { var n = document.getElementById(id); if (n) parts.push((n.textContent || '').trim()); });",
  "    if (parts.length) return parts.join(' ').trim();",
  '  }',
  "  if (el.tagName === 'INPUT') {",
  "    var t = (el.getAttribute('type') || 'text').toLowerCase();",
  "    if (t === 'submit' || t === 'button' || t === 'reset') return (el.value || '').trim();",
  '  }',
  "  var img = el.querySelector && el.querySelector('img[alt]');",
  "  if (img) return (img.getAttribute('alt') || '').trim();",
  "  if (el.getAttribute && el.getAttribute('title')) return el.getAttribute('title').trim();",
  "  var ph = el.getAttribute && el.getAttribute('placeholder');",
  "  return ((el.textContent || '') + ' ' + (ph || '')).trim();",
  '}',
  '/** Accessible lookup: role + accessible name, the robust way to hit a control. */',
  'function findByRole(role, name) {',
  "  var want = String(role || '').trim().toLowerCase();",
  "  var needle = String(name || '').trim().toLowerCase();",
  "  var all = document.querySelectorAll('button, a, input, select, textarea, [role], img, h1, h2, h3, h4, h5, h6, li');",
  '  for (var i = 0; i < all.length; i++) {',
  '    var el = all[i];',
  "    if (!el.getClientRects || el.getClientRects().length === 0) continue;",
  '    if (roleOf(el) !== want) continue;',
  "    var label = accessibleName(el).toLowerCase();",
  "    if (!needle || label.indexOf(needle) !== -1) return el;",
  '  }',
  '  return null;',
  '}',
  "function setNative(el, value) {",
  "  var proto = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;",
  "  var setter = Object.getOwnPropertyDescriptor(proto, 'value').set;",
  "  setter.call(el, value);",
  "  el.dispatchEvent(new Event('input', { bubbles: true }));",
  "  el.dispatchEvent(new Event('change', { bubbles: true }));",
  "}",
  "var ops = {",
  "  click: function (a) {",
  "    var el = a.role ? findByRole(a.role, a.name) : (a.selector ? document.querySelector(a.selector) : findByText(a.text));",
  "    if (!el) throw new Error('element not found: ' + (a.role ? a.role + ' \"' + (a.name || '') + '\"' : (a.selector || a.text)));",
  "    return one(el);",
  "  },",
  "  fill: function (a) {",
  "    var el = a.role ? findByRole(a.role, a.name) : document.querySelector(a.selector);",
  "    if (!el) throw new Error('element not found: ' + (a.role ? a.role + ' \"' + (a.name || '') + '\"' : a.selector));",
  "    setNative(el, String(a.value));",
  "    return { filled: true, value: String(a.value).slice(0, 120) };",
  "  },",
  "  read: function (a) {",
  "    var el = document.querySelector(a.selector);",
  "    if (!el) throw new Error('element not found: ' + a.selector);",
  "    if (a.attr) return el.getAttribute(a.attr);",
  "    return el.value !== undefined && el.tagName !== 'DIV' && el.tagName !== 'SPAN' ? el.value : (el.textContent || '').trim();",
  "  },",
  "  eval: function (a) {",
  "    var fn = new Function('return (' + a.code + ')');",
  "    return fn();",
  "  },",
  "  wait_for: function (a) {",
  "    var deadline = Date.now() + (a.timeoutMs || 5000);",
  "    return new Promise(function (resolveP, rejectP) {",
  "      (function check() {",
  "        var el = document.querySelector(a.selector);",
  "        if (el) return resolveP({ found: true });",
  "        if (Date.now() > deadline) return rejectP(new Error('wait_for timeout: ' + a.selector));",
  "        setTimeout(check, 120);",
  "      })();",
  "    });",
  "  },",
  '  // Measure an animation by numbers — the only way an agent without video can judge motion.',
  '  motion: function (a) {',
  "    var el = a.selector ? document.querySelector(a.selector) : document.body;",
  "    if (!el) throw new Error('element not found: ' + a.selector);",
  "    var ms = Math.min(a.ms || 800, 5000);",
  "    var samples = [];",
  "    var t0 = performance.now();",
  "    return new Promise(function (resolve) {",
  "      (function tick() {",
  "        var t = Math.round(performance.now() - t0);",
  "        var cs = getComputedStyle(el);",
  "        samples.push({ t: t, transform: cs.transform, opacity: Number(cs.opacity), props: cs.transitionProperty, dur: cs.transitionDuration, ease: cs.transitionTimingFunction, anim: cs.animationName, animDur: cs.animationDuration });",
  "        if (t < ms) requestAnimationFrame(tick);",
  "        else {",
  "          var first = samples[0], last = samples[samples.length - 1];",
  "          var nums = function (m) { if (!m || m === 'none') return [0, 0]; var p = m.match(/-?[0-9.]+/g) || []; return [Number(p[4] || 0), Number(p[5] || 0)]; };",
  "          var from = nums(first.transform), to = nums(last.transform);",
  "          resolve({",
  "            frames: samples.length,",
  "            durationMs: last.t,",
  "            distancePx: Math.round(Math.sqrt(Math.pow(to[0] - from[0], 2) + Math.pow(to[1] - from[1], 2))),",
  "            moved: Math.sqrt(Math.pow(to[0] - from[0], 2) + Math.pow(to[1] - from[1], 2)) > 0.5,",
  "            from: first.transform, to: last.transform,",
  "            opacityFrom: first.opacity, opacityTo: last.opacity,",
  "            properties: first.props, duration: first.dur, easing: first.ease,",
  "            animation: first.anim && first.anim !== 'none' ? first.anim + ' ' + first.animDur : null,",
  "            samples: samples.slice(0, 24)",
  "          });",
  "        }",
  "      })();",
  "    });",
  "  },",
  '  // Measured audit of the checkable craft/mobile/motion rules. Fuzzy items stay for the human.',
  '  audit: function () {',
  '    var findings = [];',
  '    function add(rule, detail, measured) { findings.push({ rule: rule, detail: detail, measured: measured === undefined ? null : measured }); }',
  "    function seen(el) { return el.getClientRects().length > 0; }",
  "    function tag(el) { return (el.id ? '#' + el.id : el.tagName.toLowerCase() + (el.className && typeof el.className === 'string' ? '.' + el.className.split(' ')[0] : '')); }",
  '    var i, el, cs;',
  '    // --- mobile ---',
  "    var vmeta = document.querySelector('meta[name=viewport]');",
  "    var vcontent = vmeta ? (vmeta.getAttribute('content') || '') : '';",
  "    if (!/viewport-fit=cover/.test(vcontent)) add('mobile/viewport-fit', 'viewport meta sem viewport-fit=cover (safe areas ficam 0px)', vcontent || '(sem meta viewport)');",
  "    var themes = document.querySelectorAll('meta[name=theme-color]');",
  "    if (themes.length < 2) add('mobile/theme-color', 'theme-color unico: claro/escuro sem cor propria', themes.length + ' tag(s)');",
  '    cs = getComputedStyle(document.documentElement);',
  "    var tap = cs.webkitTapHighlightColor || '';",
  "    if (tap && tap !== 'rgba(0, 0, 0, 0)') add('mobile/tap-highlight', '-webkit-tap-highlight-color nao e transparent', tap);",
  "    if (cs.overscrollBehaviorY !== 'none') add('mobile/overscroll', 'html sem overscroll-behavior: none', cs.overscrollBehaviorY);",
  '    var smallInputs = [], smallTargets = [], noTouchAction = [], fixedUnsafe = [];',
  "    document.querySelectorAll('input, textarea, select').forEach(function (el) {",
  "      var fs = parseFloat(getComputedStyle(el).fontSize);",
  "      if (fs && fs < 16) smallInputs.push(tag(el) + ':' + fs + 'px');",
  '    });',
  "    if (smallInputs.length) add('mobile/input-font', 'inputs abaixo de 16px causam zoom no iOS', smallInputs.slice(0, 6).join(', '));",
  "    document.querySelectorAll('button, a[href], [role=button], input[type=submit], input[type=button]').forEach(function (el) {",
  '      if (!seen(el)) return;',
  '      var r = el.getBoundingClientRect();',
  "      if (r.width && (r.width < 44 || r.height < 44)) smallTargets.push(tag(el) + ' ' + Math.round(r.width) + 'x' + Math.round(r.height));",
  "      var ta = getComputedStyle(el).touchAction;",
  "      if (ta !== 'manipulation' && ta !== 'none') noTouchAction.push(tag(el));",
  '    });',
  "    if (smallTargets.length) add('mobile/touch-target', 'alvos abaixo de 44x44px', smallTargets.slice(0, 6).join(' | '));",
  "    if (noTouchAction.length) add('mobile/touch-action', 'sem touch-action: manipulation (atraso de 300ms)', noTouchAction.slice(0, 6).join(', '));",
  "    document.querySelectorAll('header, footer, nav, aside, [class*=fixed], [class*=bar], [class*=fab]').forEach(function (el) {",
  '      var c = getComputedStyle(el);',
  "      if (c.position !== 'fixed') return;",
  '      var inline = el.getAttribute(\'style\') || \'\';',
  "      if (/env\\(/.test(inline)) return;",
  '      if (parseFloat(c.paddingBottom) < 1 && parseFloat(c.paddingTop) < 1) fixedUnsafe.push(tag(el));',
  '    });',
  "    if (fixedUnsafe.length) add('mobile/safe-area', 'elemento fixo sem padding de safe-area', fixedUnsafe.slice(0, 6).join(', '));",
  '    var ungatedHover = [], longDur = [], easeIn = [], allProp = [], anims = [], motionInventory = [];',
  "    try {",
  '      Array.prototype.forEach.call(document.styleSheets, function (sheet) {',
  '        var rules; try { rules = sheet.cssRules; } catch (e) { return; }',
  '        (function walk(list, gated) {',
  '          Array.prototype.forEach.call(list, function (rule) {',
  '            if (rule.media) {',
  "              var cond = String(rule.conditionText || (rule.media && rule.media.mediaText) || '');",
  "              return walk(rule.cssRules, gated || /hover:\\s*hover/.test(cond));",
  '            }',
  "            if (rule.selectorText && /:hover/.test(rule.selectorText) && !gated) ungatedHover.push(rule.selectorText.slice(0, 70));",
  "            if (rule.name && rule.cssText && /scale\\(0\\)/.test(rule.cssText)) anims.push('@keyframes ' + rule.name + ' usa scale(0)');",
  '          });',
  '        })(rules, false);',
  '      });',
  '    } catch (e) {}',
  "    if (ungatedHover.length) add('mobile/hover-gate', ':hover fora de @media (hover: hover) and (pointer: fine)', ungatedHover.slice(0, 6).join(' | '));",
  '    // --- motion ---',
  "    document.querySelectorAll('*').forEach(function (el) {",
  '      var c = getComputedStyle(el);',
  "      if (c.transitionProperty && c.transitionProperty !== 'none') {",
  "        if (c.transitionProperty === 'all') allProp.push(tag(el));",
  "        var d = Math.max.apply(null, String(c.transitionDuration).split(',').map(function (x) { return parseFloat(x) || 0; }));",
  "        if (d > 0.3) longDur.push(tag(el) + ' ' + Math.round(d * 1000) + 'ms');",
  "        if (/ease-in(?!-out)/.test(c.transitionTimingFunction)) easeIn.push(tag(el) + ' ' + c.transitionTimingFunction);",
  "        motionInventory.push({ el: tag(el), props: c.transitionProperty, dur: c.transitionDuration, ease: c.transitionTimingFunction });",
  '      }',
  "      if (c.animationName && c.animationName !== 'none') motionInventory.push({ el: tag(el), anim: c.animationName, dur: c.animationDuration });",
  '    });',
  "    if (allProp.length) add('motion/transition-all', 'transition: all anima propriedades que voce nao escolheu', allProp.slice(0, 6).join(', '));",
  "    if (longDur.length) add('motion/duration', 'duracao de UI acima de 300ms', longDur.slice(0, 6).join(', '));",
  "    if (easeIn.length) add('motion/ease-in', 'ease-in em elemento de UI (atrasa o momento que o usuario olha)', easeIn.slice(0, 6).join(', '));",
  "    if (anims.length) add('motion/scale-zero', 'keyframe animando a partir de scale(0)', anims.slice(0, 4).join(', '));",
  "    if (!/prefers-reduced-motion/.test(Array.prototype.map.call(document.styleSheets, function (s) { try { return Array.prototype.map.call(s.cssRules, function (r) { return r.cssText; }).join(''); } catch (e) { return ''; } }).join(''))) add('motion/reduced-motion', 'nenhuma regra @media (prefers-reduced-motion)', null);",
  '    // --- craft ---',
  '    var clickableDivs = [];',
  "    document.querySelectorAll('div[onclick], span[onclick], div[role=button]').forEach(function (el) { if (!/^(button|a)$/i.test(el.tagName)) clickableDivs.push(tag(el)); });",
  "    if (clickableDivs.length) add('craft/clickable-div', 'div/span clicavel em vez de button (sem foco nem teclado)', clickableDivs.slice(0, 6).join(', '));",
  '    var invisibleDisabled = [], lowContrast = [];',
  "    document.querySelectorAll('button, input, [disabled]').forEach(function (el) {",
  "      if (!el.disabled || !seen(el)) return;",
  '      var c = getComputedStyle(el);',
  "      var op = Number(c.opacity);",
  "      if (op && op < 0.5 && (el.textContent || '').trim()) invisibleDisabled.push(tag(el) + ' opacity ' + op);",
  '    });',
  "    if (invisibleDisabled.length) add('craft/disabled-legible', 'estado desabilitado apagado a ponto de esconder o rotulo', invisibleDisabled.slice(0, 6).join(', '));",
  '    function bgOf(node) {',
  "      var n = node;",
  "      while (n && n !== document.documentElement) {",
  "        var c = getComputedStyle(n);",
  "        if (c.backgroundColor && c.backgroundColor !== 'rgba(0, 0, 0, 0)' && c.backgroundColor !== 'transparent') return c.backgroundColor;",
  '        n = n.parentElement;',
  '      }',
  "      return getComputedStyle(document.body).backgroundColor || 'rgb(255, 255, 255)';",
  '    }',
  '    function lum(rgb) {',
  "      var p = String(rgb).match(/[0-9.]+/g) || [0, 0, 0];",
  '      var c = [Number(p[0]), Number(p[1]), Number(p[2])].map(function (v) { v = v / 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); });',
  '      return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];',
  '    }',
  '    function ratio(a, b) { var l1 = lum(a), l2 = lum(b); var hi = Math.max(l1, l2), lo = Math.min(l1, l2); return (hi + 0.05) / (lo + 0.05); }',
  "    document.querySelectorAll('p, span, a, li, h1, h2, h3, h4, button, label, td, th').forEach(function (el) {",
  "      if (!seen(el) || !(el.textContent || '').trim()) return;",
  '      var c = getComputedStyle(el);',
  "      if (!c.color || c.visibility === 'hidden') return;",
  '      var r = ratio(c.color, bgOf(el));',
  "      var size = parseFloat(c.fontSize) || 16;",
  "      var bold = (parseInt(c.fontWeight, 10) || 400) >= 700;",
  "      var large = size >= 24 || (bold && size >= 18.66);",
  '      var min = large ? 3 : 4.5;',
  '      if (r < min) lowContrast.push(tag(el) + \' \' + r.toFixed(2) + \':1\');',
  '    });',
  "    if (lowContrast.length) add('craft/contrast', 'contraste de texto abaixo do minimo (4.5:1, ou 3:1 em texto grande)', lowContrast.slice(0, 8).join(', '));",
  '    var noOutline = [];',
  "    document.querySelectorAll('button, a[href], input, select, textarea, [tabindex]').forEach(function (el) {",
  '      var c = getComputedStyle(el);',
  "      if (c.outlineStyle === 'none' && !/focus-visible/.test(el.className || '')) noOutline.push(tag(el));",
  '    });',
  "    if (noOutline.length) add('craft/focus-visible', 'sem outline: dependa de :focus-visible com anel visivel (conferir manualmente)', noOutline.slice(0, 8).join(', '));",
  '    return { findings: findings, count: findings.length, motionInventory: motionInventory.slice(0, 40), scanned: document.querySelectorAll("*").length };',
  "  },",
  "  // Page-side ops that keep the shim alive: the result is posted before the page reloads.",
  "  reload: function () { setTimeout(function () { location.reload(); }, 60); return { reloading: true, url: location.href }; },",
  "  scroll: function (a) {",
  "    function containerOf(el) {",
  "      var n = el;",
  "      while (n && n !== document.body) {",
  "        var st = getComputedStyle(n);",
  "        if (/(auto|scroll)/.test(st.overflowY) && n.scrollHeight > n.clientHeight + 4) return n;",
  "        n = n.parentElement;",
  "      }",
  "      return document.scrollingElement || document.documentElement;",
  "    }",
  "    var box = a.selector ? document.querySelector(a.selector) : null;",
  "    var container = box ? containerOf(box) : (document.scrollingElement || document.documentElement);",
  "    var before = container.scrollTop;",
  "    if (box) box.scrollIntoView({ block: 'center', behavior: a.smooth ? 'smooth' : 'auto' });",
  "    else if (a.to === 'bottom') container.scrollTop = container.scrollHeight;",
  "    else if (a.to === 'top') container.scrollTop = 0;",
  "    else if (typeof a.to === 'number') container.scrollTop = a.to;",
  "    else if (typeof a.by === 'number') container.scrollTop = container.scrollTop + a.by;",
  "    return new Promise(function (resolve) {",
  "      setTimeout(function () {",
  "        var max = Math.max(container.scrollHeight - container.clientHeight, 0);",
  "        var isPage = container === document.scrollingElement || container === document.documentElement;",
  "        resolve({ scrollY: Math.round(window.scrollY), scrollX: Math.round(window.scrollX), containerScrollTop: Math.round(container.scrollTop), atBottom: container.scrollTop >= max - 2, container: isPage ? 'page' : (container.tagName.toLowerCase() + (container.id ? '#' + container.id : '')), before: Math.round(before), targetVisible: box ? (box.getBoundingClientRect().top >= 0 && box.getBoundingClientRect().bottom <= (window.innerHeight || 0)) : null });",
  "      }, a.smooth ? 500 : 60);",
  "    });",
  "  },",
  "  wait_stable: function (a) {",
  "    var quiet = Math.min(a.quietMs || 500, 5000), cap = Math.min(a.timeoutMs || 10000, 30000);",
  "    return new Promise(function (resolve) {",
  "      var last = Date.now(), started = Date.now(), raf = 0;",
  "      var obs = new MutationObserver(function () { last = Date.now(); });",
  "      try { obs.observe(document.documentElement, { subtree: true, childList: true, attributes: true, characterData: true }); } catch (e) {}",
  "      var tick = function () { last = Date.now(); raf = requestAnimationFrame(tick); };",
  "      raf = requestAnimationFrame(tick);",
  "      (function check() {",
  "        var idle = Date.now() - last, busy = document.readyState !== 'complete';",
  "        if ((idle >= quiet && !busy) || Date.now() - started >= cap) {",
  "          try { obs.disconnect(); } catch (e) {}",
  "          try { cancelAnimationFrame(raf); } catch (e) {}",
  "          resolve({ stable: idle >= quiet && !busy, quietMs: idle, elapsedMs: Date.now() - started });",
  "          return;",
  "        }",
  "        setTimeout(check, 100);",
  "      })();",
  "    });",
  "  },",
  "  upload: function (a) {",
  "    var input = a.selector ? document.querySelector(a.selector) : document.querySelector('input[type=file]');",
  "    if (!input) throw new Error('file input not found: ' + (a.selector || 'input[type=file]'));",
  "    var bin = atob(String(a.value || '')), bytes = new Uint8Array(bin.length);",
  "    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  "    var file = new File([bytes], a.name || 'upload.bin', { type: a.mime || 'application/octet-stream' });",
  "    var dt = new DataTransfer();",
  "    dt.items.add(file);",
  "    input.files = dt.files;",
  "    input.dispatchEvent(new Event('input', { bubbles: true }));",
  "    input.dispatchEvent(new Event('change', { bubbles: true }));",
  "    return { uploaded: true, name: file.name, bytes: bytes.length };",
  "  },",
  "  console_dump: function () { return { entries: buffer }; },",
  "};",
].join('\n')

/** The composed frozen shim: header + shared ops + footer, byte-identical to the historical single string. */
export const BUNDLED_SHIM_JS = [
  '(function(){',
  'if (window.__DSH_PROTOTYPE_SHIM__) return;',
  `window.__DSH_PROTOTYPE_SHIM__ = ${JSON.stringify(BUNDLED_SHIM_VERSION)};`,
  'var buffer = [];',
  'var MAX = 200;',
  'function push(level, text) {',
  '  var entry = { level: level, text: String(text), time: new Date().toISOString() };',
  '  buffer.push(entry); if (buffer.length > MAX) buffer.shift();',
  "  try { parent.postMessage({ source: 'dsh-prototype-shim', console: entry }, '*'); } catch (e) {}",
  '}',
  "['error','warn'].forEach(function (level) {",
  '  var original = console[level].bind(console);',
  '  console[level] = function () {',
  "    var parts = []; for (var i = 0; i < arguments.length; i++) { try { parts.push(typeof arguments[i] === 'object' ? JSON.stringify(arguments[i]) : String(arguments[i])); } catch (e) { parts.push('[unserializable]'); } }",
  "    push(level, parts.join(' '));",
  '    original.apply(null, arguments);',
  '  };',
  '});',
  "window.addEventListener('error', function (e) { push('error', 'Uncaught: ' + e.message + ' @ ' + (e.filename || '') + ':' + (e.lineno || 0)); });",
  "window.addEventListener('unhandledrejection', function (e) { push('error', 'Unhandled rejection: ' + (e.reason && (e.reason.stack || e.reason.message) || String(e.reason))); });",
  PAGE_OPS_SOURCE,
  "window.addEventListener('message', function (e) {",
  "  var cmd = e.data;",
  "  if (!cmd || cmd.source !== 'dsh-prototype' || !cmd.id) return;",
  '  var op = ops[cmd.op];',
  "  if (!op) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: false, error: 'unknown op ' + cmd.op }, '*'); return; }",
  '  Promise.resolve().then(function () { return op(cmd); })',
  "    .then(function (result) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: true, result: result, consoleTail: buffer.slice(-20) }, '*'); })",
  "    .catch(function (err) { parent.postMessage({ source: 'dsh-prototype-shim', id: cmd.id, ok: false, error: String((err && err.message) || err) }, '*'); });",
  '});',
  '})();',
].join('\n')

/**
 * The same ops as an expression for drivers that execute them without the
 * postMessage plumbing (the full-scope WebContentsView in the desktop app).
 * Returns the ops object plus `findByText` for text-based waiting.
 */
export function pageOpsExpression() {
  return `(function(){\n${PAGE_OPS_SOURCE}\n;return { ops: ops, findByText: findByText, findByRole: findByRole };\n})()`
}
